import type { TaskModule } from "@/types";

export const APP_NAME = "Lambdata";
export const APP_TAGLINE =
  "Infrastructure africaine souveraine de collecte de données IA";

/** Langues de l'interface (paramètres) */
export const APP_UI_LANGUAGES = [
  { code: "fr", label: "Français" },
  { code: "en", label: "English" },
  { code: "ar", label: "العربية" },
  { code: "pt", label: "Português" },
  { code: "sw", label: "Kiswahili" },
] as const;

/** Langues pour lesquelles l'utilisateur peut contribuer */
export const AFRICAN_LANGUAGES = [
  { code: "am", label: "Amharique" },
  { code: "ar", label: "Arabe" },
  { code: "bm", label: "Bambara" },
  { code: "ber", label: "Berbère / Tamazight" },
  { code: "dyu", label: "Dioula" },
  { code: "ee", label: "Éwé" },
  { code: "en", label: "Anglais" },
  { code: "ff", label: "Peulh / Fulfulde" },
  { code: "fon", label: "Fon" },
  { code: "fr", label: "Français" },
  { code: "ha", label: "Hausa" },
  { code: "ig", label: "Igbo" },
  { code: "kg", label: "Kikongo" },
  { code: "ln", label: "Lingala" },
  { code: "mg", label: "Malgache" },
  { code: "mos", label: "Mooré" },
  { code: "ny", label: "Chichewa" },
  { code: "om", label: "Oromo" },
  { code: "pt", label: "Portugais" },
  { code: "rn", label: "Kirundi" },
  { code: "rw", label: "Kinyarwanda" },
  { code: "sn", label: "Shona" },
  { code: "so", label: "Somali" },
  { code: "st", label: "Sesotho" },
  { code: "sw", label: "Swahili" },
  { code: "ti", label: "Tigrinya" },
  { code: "tn", label: "Setswana" },
  { code: "tw", label: "Twi" },
  { code: "wo", label: "Wolof" },
  { code: "xh", label: "Xhosa" },
  { code: "yo", label: "Yoruba" },
  { code: "zu", label: "Zoulou" },
] as const;

export const AFRICAN_ETHNICITIES = [
  { code: "amhara", label: "Amhara" },
  { code: "arab_mag", label: "Arabe (Maghreb)" },
  { code: "bambara", label: "Bambara" },
  { code: "berber", label: "Berbère" },
  { code: "diola", label: "Diola" },
  { code: "ewe", label: "Éwé" },
  { code: "fon", label: "Fon" },
  { code: "fulani", label: "Peul / Fulani" },
  { code: "hausa", label: "Hausa" },
  { code: "hutu", label: "Hutu" },
  { code: "igbo", label: "Igbo" },
  { code: "kikuyu", label: "Kikuyu" },
  { code: "lingala", label: "Lingala" },
  { code: "luo", label: "Luo" },
  { code: "malinke", label: "Malinké" },
  { code: "mossi", label: "Mossi" },
  { code: "oromo", label: "Oromo" },
  { code: "other", label: "Autre / préfère ne pas dire" },
  { code: "serer", label: "Sérère" },
  { code: "somali", label: "Somali" },
  { code: "soninke", label: "Soninké" },
  { code: "tutsi", label: "Tutsi" },
  { code: "wolof", label: "Wolof" },
  { code: "xhosa", label: "Xhosa" },
  { code: "yoruba", label: "Yoruba" },
  { code: "zulu", label: "Zoulou" },
] as const;

export const AFRICAN_COUNTRIES = [
  { code: "DZ", label: "Algérie", flag: "🇩🇿" },
  { code: "AO", label: "Angola", flag: "🇦🇴" },
  { code: "BJ", label: "Bénin", flag: "🇧🇯" },
  { code: "BW", label: "Botswana", flag: "🇧🇼" },
  { code: "BF", label: "Burkina Faso", flag: "🇧🇫" },
  { code: "BI", label: "Burundi", flag: "🇧🇮" },
  { code: "CM", label: "Cameroun", flag: "🇨🇲" },
  { code: "CV", label: "Cap-Vert", flag: "🇨🇻" },
  { code: "TD", label: "Tchad", flag: "🇹🇩" },
  { code: "KM", label: "Comores", flag: "🇰🇲" },
  { code: "CG", label: "Congo", flag: "🇨🇬" },
  { code: "CD", label: "RD Congo", flag: "🇨🇩" },
  { code: "CI", label: "Côte d'Ivoire", flag: "🇨🇮" },
  { code: "DJ", label: "Djibouti", flag: "🇩🇯" },
  { code: "EG", label: "Égypte", flag: "🇪🇬" },
  { code: "GQ", label: "Guinée équatoriale", flag: "🇬🇶" },
  { code: "ER", label: "Érythrée", flag: "🇪🇷" },
  { code: "SZ", label: "Eswatini", flag: "🇸🇿" },
  { code: "ET", label: "Éthiopie", flag: "🇪🇹" },
  { code: "GA", label: "Gabon", flag: "🇬🇦" },
  { code: "GM", label: "Gambie", flag: "🇬🇲" },
  { code: "GH", label: "Ghana", flag: "🇬🇭" },
  { code: "GN", label: "Guinée", flag: "🇬🇳" },
  { code: "GW", label: "Guinée-Bissau", flag: "🇬🇼" },
  { code: "KE", label: "Kenya", flag: "🇰🇪" },
  { code: "LS", label: "Lesotho", flag: "🇱🇸" },
  { code: "LR", label: "Liberia", flag: "🇱🇷" },
  { code: "LY", label: "Libye", flag: "🇱🇾" },
  { code: "MG", label: "Madagascar", flag: "🇲🇬" },
  { code: "MW", label: "Malawi", flag: "🇲🇼" },
  { code: "ML", label: "Mali", flag: "🇲🇱" },
  { code: "MR", label: "Mauritanie", flag: "🇲🇷" },
  { code: "MU", label: "Maurice", flag: "🇲🇺" },
  { code: "MA", label: "Maroc", flag: "🇲🇦" },
  { code: "MZ", label: "Mozambique", flag: "🇲🇿" },
  { code: "NA", label: "Namibie", flag: "🇳🇦" },
  { code: "NE", label: "Niger", flag: "🇳🇪" },
  { code: "NG", label: "Nigeria", flag: "🇳🇬" },
  { code: "RW", label: "Rwanda", flag: "🇷🇼" },
  { code: "ST", label: "São Tomé-et-Príncipe", flag: "🇸🇹" },
  { code: "SN", label: "Sénégal", flag: "🇸🇳" },
  { code: "SC", label: "Seychelles", flag: "🇸🇨" },
  { code: "SL", label: "Sierra Leone", flag: "🇸🇱" },
  { code: "SO", label: "Somalie", flag: "🇸🇴" },
  { code: "ZA", label: "Afrique du Sud", flag: "🇿🇦" },
  { code: "SS", label: "Soudan du Sud", flag: "🇸🇸" },
  { code: "SD", label: "Soudan", flag: "🇸🇩" },
  { code: "TZ", label: "Tanzanie", flag: "🇹🇿" },
  { code: "TG", label: "Togo", flag: "🇹🇬" },
  { code: "TN", label: "Tunisie", flag: "🇹🇳" },
  { code: "UG", label: "Ouganda", flag: "🇺🇬" },
  { code: "ZM", label: "Zambie", flag: "🇿🇲" },
  { code: "ZW", label: "Zimbabwe", flag: "🇿🇼" },
] as const;

export const TASK_MODULES: TaskModule[] = [
  {
    id: "audio",
    title: "Collecte vocale",
    description: "Enregistrez des phrases dans vos langues",
    icon: "Mic",
    color: "from-violet-400/30 to-violet-600/10",
    href: "/tasks/audio",
    available: true,
  },
  {
    id: "translation",
    title: "Traduction",
    description: "Traduisez phrase par phrase",
    icon: "Languages",
    color: "from-sky-400/30 to-sky-600/10",
    href: "/tasks/translation",
    available: true,
  },
  {
    id: "image",
    title: "Images culturelles",
    description: "Capturez et annotez des images",
    icon: "Camera",
    color: "from-amber-400/30 to-amber-600/10",
    href: "/tasks/image",
    available: true,
  },
  {
    id: "video",
    title: "Vidéos courtes",
    description: "Contribuez des vidéos locales",
    icon: "Video",
    color: "from-rose-400/30 to-rose-600/10",
    href: "/tasks/video",
    available: false,
  },
  {
    id: "validation",
    title: "Validation communautaire",
    description: "Validez les contributions des autres",
    icon: "CheckCircle2",
    color: "from-emerald-400/30 to-emerald-600/10",
    href: "/tasks/validation",
    available: true,
  },
  {
    id: "text",
    title: "Texte & correction",
    description: "Corrigez et classifiez du texte",
    icon: "FileText",
    color: "from-teal-400/30 to-teal-600/10",
    href: "/tasks/text",
    available: false,
  },
];

export const IMAGE_CATEGORIES = [
  { code: "food", label: "Nourriture" },
  { code: "agriculture", label: "Agriculture" },
  { code: "craft", label: "Artisanat" },
  { code: "market", label: "Marchés" },
  { code: "music", label: "Musique & instruments" },
  { code: "clothing", label: "Habits & tissus" },
  { code: "architecture", label: "Architecture" },
  { code: "other", label: "Autre" },
] as const;

export const XP_PER_LEVEL = 10000;
